const ContentIdentityPolka = [
  {
    hds: "Subtrate",
    hdsAT1: "Rust",
    hdsAT2: "Node Js",
    hdsAT3: "Yarn",
    hds2: "LLVM",
    hds2AT1: "Substrate Node & Frontend Teamplate",
    hds2AT2: "",
    hds2AT3: "",
    hds2AT4: "",
    hds3:
      "Follow the commands below to prepare the environment. Some can be skipped if already installed.",
    hds3AT1: "$ sudo apt update",
    hds4:
      "$ sudo apt install -y build-essential ocaml ocamlbuild automake autoconf libtool wget python libssl-dev git cmake perl pkg-config curl llvm-10 clang-10 libclang-10-dev",
    hds4AT1: "$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
    hds5: "$ source ~/.cargo/env",
    hds5AT1:
      "$ curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -",
    hds6: "$ sudo apt-get install -y nodejs",
    hds6AT1: "$ sudo npm install -g yarn",
    hds6AT2: "Test the installation by running the following commands",
    hds6AT3: "$ rustup --version",
    hds6AT4: "$ cargo --version",
    hds6AT5: "$ llvm-ar-10 --version",
    hds6AT6: "$ node --version",
    hds6AT7: "$ yarn --version",
    termOne: "Requirement",
    termTwo: "",
    user: "Like What You See ?",
    userProfile: "https://raw.githubusercontent.com/Agin-DropDisco/encode-hclub/main/PORTIS/groot.webp",
    hds6ATss: "",
    hds6ATss1: "",
    hds6ATss2: "",
    hds6ATss3: "",
  },
  {
    hds:
      "Clone Substrate Node Template and Frontend Template and run the initialization script",
    hdsAT1:
      "$ git clone https://github.com/substrate-developer-hub/substrate-node-template.git",
    hdsAT2: "$ cd substrate-node-template",
    hdsAT3: "$ make init ",
    hds2: "$ make build",
    hds2AT1: "Clone Polkadot code and run the initialization script",
    hds2AT2: "$ git clone https://github.com/paritytech/polkadot.git",
    hds2AT3: "$ cd polkadot",
    hds2AT4: "$ cargo build --release",
    hds3: "Run Substrate Node Template",
    hds3AT1: "$ cd substrate-node-template",
    hds4: "$ ./target/release/node-template --dev --tmp",
    hds4AT1: "",
    hds5: "",
    hds5AT1: "",
    hds6: "",
    hds6AT1: "",
    hds6AT2: "Connect to Polkadot Node",
    hds6AT3: "$ cd polkadot",
    hds6AT4: "./target/release/polkadot --name TheWeirdBrother --dev",
    hds6AT5: "",
    hds6AT6: "",
    hds6AT7: "",
    termOne: "",
    termTwo: "",
    user: "Like What You See ?",
    userProfile: "https://raw.githubusercontent.com/Agin-DropDisco/encode-hclub/main/PORTIS/groot.webp",
    hds6ATss: "SCREEN SHOOT",
    hds6ATss1: "https://ibb.co/r7sY5SF",
    hds6ATss2: "https://ibb.co/mv0JrMf",
    hds6ATss3: " == DONE ==",
  },
  ];
  export  default ContentIdentityPolka;