const ContentTelemetryPolka = [
  {
    hds: "Subtrate",
    hdsAT1: "Rust",
    hdsAT2: "Node Js",
    hdsAT3: "Yarn",
    hds2: "LLVM",
    hds2AT1: "Substrate Node & Polkadot Node Template",
    hds2AT2: "",
    hds2AT3: "",
    hds2AT4: "",
    hds3:
      "Follow the commands below to prepare the environment. Some can be skipped if already installed.",
    hds3AT1: "$ sudo apt update",
    hds4:
      "$ sudo apt install -y build-essential ocaml ocamlbuild automake autoconf libtool wget python libssl-dev git cmake perl pkg-config curl llvm-10 clang-10 libclang-10-dev",
    hds4AT1: "$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
    hds5: "$ source ~/.cargo/env",
    hds5AT1:
      "$ curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -",
    hds6: "$ sudo apt-get install -y nodejs",
    hds6AT1: "$ sudo npm install -g yarn",
    hds6AT2: "Test the installation by running the following commands",
    hds6AT3: "$ rustup --version",
    hds6AT4: "$ cargo --version",
    hds6AT5: "$ llvm-ar-10 --version",
    hds6AT6: "$ node --version",
    hds6AT7: "$ yarn --version",
    termOne: "Requirement",
    termTwo: "",
    user: "Like What You See ?",
    userProfile: "https://raw.githubusercontent.com/Agin-DropDisco/encode-hclub/main/PORTIS/groot.webp",
    hds6ATss: "",
    hds6ATss1: "",
    hds6ATss2: "",
    hds6ATss3: "",
    
  },
  {
    hds:
      "Clone Polkadot Node and run the initialization script",
    hdsAT1:
      "$ git clone https://github.com/paritytech/polkadot.git",
    hdsAT2: "$ cd polkadot",
    hdsAT3: "$ cargo build --release",
    hds2: "",
    hds2AT1:
      "",
    hds2AT2: "",
    hds2AT3: "",
    hds2AT4: "",
    hds3: "noted: If we got an issue when building with Rust, we can downgrading Rust.",
    hds3AT1: "$ rustup toolchain install nightly-2020-10-06",
    hds4: "$ rustup install nightly-2020-10-06",
    hds4AT1: "$ rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06",
    hds5: "$ rustup install cargo +nightly-2020-10-06 ",
    hds5AT1: "",
    hds6: "",
    hds6AT1: "",
    hds6AT2: "Let's connect to Polkadot Mainnet",
    hds6AT3: "$ cd polkadot",
    hds6AT4: "./target/release/polkadot --chain=polkadot --name TheWeirdBrother",
    hds6AT5: "",
    hds6AT6: "",
    hds6AT7: "",
    termOne: "",
    termTwo: "",
    user: "Like What You See ?",
    userProfile: "https://raw.githubusercontent.com/Agin-DropDisco/encode-hclub/main/PORTIS/groot.webp",
    hds6ATss: "SCREEN SHOOT",
    hds6ATss1: "https://ibb.co/4WmZpMz",
    hds6ATss2: "https://ibb.co/CWxs5H0",
    hds6ATss3: " == DONE ==",
  },
];
export default ContentTelemetryPolka;
